### ISSUE TITLE
Intermittently unable to start viewer

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#10]
Using View() on the `babynames` tibble, I occasionally get the message below.
![view-failure](https://user-images.githubusercontent.com/911566/47291170-a4d2ea80-d5d0-11e8-90e5-da3176824aad.png)

**Comment by garrettgman** [comment]
This would be a learnr side effect of how learnr is implemented. If you are still experience the same behavior, you could file a bug report at https://github.com/rstudio/learnr/issues.

But, to be honest, I suspect that the optimal solution will be to have people use the data viewer in their IDE when tutorials and IDEs are better integrated.
