### ISSUE TITLE
Making navigation easier

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#13]
I finish "tidyverse", and there's a button to go back to the previous topic, but how do I get to the next one in "Work with Data"?  I can click on "Work with Data" to get the welcome page and then select "Isolating Data with dplyr", or click the hamburger menu and select it, but neither is immediately obvious.

**Comment by garrettgman** [comment]
I moved this issue to the RStudio Cloud repository, https://github.com/rstudio/lucid-cloudyr/issues/1005
