### ISSUE TITLE
"Continue" button does nothing

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#14]
In "The history of your name" the Continue button doesn't do anything, but I was able to click "select()" in the menu on the left (image below)
![continue-does-nothing](https://user-images.githubusercontent.com/911566/47291328-33e00280-d5d1-11e8-9896-b639eee2e9ad.png)

**Comment by gvwilson** [comment]
Same thing shows up in a later tutorial
![screen shot 2018-10-22 at 9 33 59 am](https://user-images.githubusercontent.com/911566/47295503-c7b7cb80-d5dd-11e8-960f-70834f86b0d4.png)

**Comment by noew** [comment]
I have the same issue. "Continue" works once, or not at all, with all the primer lessons.
![continue_does_nothing](https://user-images.githubusercontent.com/13108968/51442188-39b8b300-1ca8-11e9-845a-feaabe09c639.png)

**Comment by garrettgman** [comment]
Thanks all. This seems to be related to a learnr bug that we believe is fixed. If anyone continues to see this behavior, please reopen the issue here: https://github.com/rstudio/learnr/issues/50
