### ISSUE TITLE
Blurry image

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#21]
The text in visualize-data/01-bar-charts/www/images/positions.png is slightly blurry for me - is it possible to create an SVG version of this image?

**Comment by garrettgman** [comment]
We can export a graph from ggplot2 in SVG format, but I don't have access to a program that can then apply a perspective transform to the SVG image to make the background for that image. Do you have one in mind? Would Adobe Illustrator handle that?

**Comment by gvwilson** [comment]
I don't know if Illustrator would handle it, but I think the easiest way to find out is to get a licensed copy and try :-)
