### ISSUE TITLE
Wrong starter code for line plot example?

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#33]
In the first exercise for `geom_line` in 06-line-graphs.md, the starter code seems to be from the `mpg` dataset, and doesn't include a line plot, so I'm unclear why it's being provided.
![screen shot 2018-10-22 at 2 52 35 pm](https://user-images.githubusercontent.com/911566/47312432-54787e80-d60a-11e8-8ccf-906cc2e6b1bc.png)

**Comment by gvwilson** [comment]
Later: same tutorial, section titled "Multiple lines" (in discussion of whipsawing), the starter code seems to be a histogram from the diamonds data set.
![screen shot 2018-10-22 at 2 56 04 pm](https://user-images.githubusercontent.com/911566/47312563-b3d68e80-d60a-11e8-97b9-5775918d5f8e.png)

**Comment by gvwilson** [comment]
And again in the next exercise: the starter code is the wrong dataset and the wrong kind of visualization for the exercise
![screen shot 2018-10-22 at 2 58 33 pm](https://user-images.githubusercontent.com/911566/47312686-031cbf00-d60b-11e8-9359-9dc78bc8c943.png)

**Comment by gvwilson** [comment]
And again with line types:
![screen shot 2018-10-22 at 3 01 04 pm](https://user-images.githubusercontent.com/911566/47312805-5727a380-d60b-11e8-90df-3d24a7b104a9.png)

**Comment by garrettgman** [comment]
This is weird. The code isn't in [the .Rmd file](https://github.com/rstudio-education/primers/blob/master/visualize-data/06-line-graphs/06-line-graphs.Rmd), which makes me suspect that it is some type of local or server-level caching.

I'm leaving this open to double-check on the next redeploy.
