### ISSUE TITLE
Strange quoted text output in 02-Vis-Basics

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#4]
The following popped up as output for a question in 02-Vis-Basics - looks odd.
![aesthetic-4](https://user-images.githubusercontent.com/911566/47290893-920be600-d5cf-11e8-832d-acf865e26125.png)

**Comment by garrettgman** [comment]
I agree this is odd! I'm no longer seeing it. Perhaps it was fixed with a learnr update.
