### ISSUE TITLE
bind_rows behavior not as described

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#58]
In 03-join-datasets.Rmd, the discussion of naming the source of data in `bind_rows` says, "bind_rows() will use the character string as the name of a new column that displays the name of the data set that each row comes from (as determined by the names in the list)." However, when I run:

```
bands <- list(df1 = band, 
              df2 = band2)

band %>% bind_rows(band2, .id = "origin")
```

the values in the column "origin" are `"1"` and `"2"`, not (as I expected) `"df1"` and `"df2"`.

**Comment by garrettgman** [comment]
Good catch! It should have been:

```
bands %>% bind_rows(.id = "origin")
```
