### ISSUE TITLE
First use of pmap should use named arguments

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#64]
The discussion of `pmap` described the use of named arguments; the first example (ANOVA across three models) doesn't use them. Introduce another example that does to make the ramp a little gentler?

**Comment by garrettgman** [comment]
This seems to cover it (after the highlight):

<img width="734" alt="Screen Shot 2019-10-25 at 4 39 46 PM" src="https://user-images.githubusercontent.com/85014/67603152-1b577a80-f746-11e9-80e6-f7d7c1e7a06b.png">

It is the first example of pmap in Iterate > Multiple Vectors
