### ISSUE TITLE
?help doesn't bold text properly

### ISSUE THREAD

**Issue by gvwilson** [rstudio-education/primers#7]
When using `?help`, the backspace characters used to add underlining/bold to text don't work, so the underscores are displayed:
![bold-help](https://user-images.githubusercontent.com/911566/47290974-f0d15f80-d5cf-11e8-9ed3-97a132d9c3c0.png)

**Comment by garrettgman** [comment]
I agree. This is an open issue in learnr. You can follow the progress here, https://github.com/rstudio/learnr/issues/16
