### ISSUE TITLE
typo in isolating data with dplr primer

### ISSUE THREAD

**Issue by rcantor13** [rstudio-education/primers#81]
just starting w R and RStudio Cloud! Also new to github. So feel free to let me know how to do all this...

I found a small typo on the Isolating Data with dplyr primer.
The one_of example in the table is missing a closing parentheses. :blush:
one_of() Columns whose name appear in the given set select(babynames, one_of(c("sex", "gender"))
![image](https://user-images.githubusercontent.com/17282300/57869551-203cf900-77ba-11e9-99ad-e71d91f935cd.png)

**Comment by g0bananas** [comment]
I was about to submit this issue too. Good call out
